In [1]:
# Run this script first
# NOTE: This script is unsolved - some of the code has been removed
# and is to be completed in demonstration

In [2]:
# Import libraries
from __future__ import print_function
import sys
from datetime import datetime
import time
import pandas as pd

In [3]:
print("Start time: " + str(datetime.now()))

Start time: 2018-08-16 12:59:58.066197

In [5]:
file_in = "Resources/SFPD_CrimeIncidents_2018.csv"
file_out_dupes ="Resources/SF_Police_Department_Incidents_dupes.csv"
# read in CSV
df = pd.read_csv(file_in)
df.head()

,IncidntNum,Category,Descript,DayOfWeek,Date,Time,PdDistrict,Resolution,Address,X,Y,Location,PdId
0,189014013,NON-CRIMINAL,"STAY AWAY OR COURT ORDER, NON-DV RELATED",Monday,01/01/2018,22:37,TARAVAL,"ARREST, BOOKED",3500 Block of 19TH AV,-122.474829,37.723976,"(37.723975823482135, -122.47482947577244)",18901401371024
1,186095971,OTHER OFFENSES,OBSCENE PHONE CALLS(S),Monday,01/01/2018,08:00,TENDERLOIN,NONE,500 Block of EDDY ST,-122.416711,37.783357,"(37.78335703909351, -122.41671073384802)",18609597119050
2,186084021,FRAUD,"CREDIT CARD, THEFT BY USE OF",Monday,01/01/2018,00:01,NORTHERN,NONE,1200 Block of EDDY ST,-122.428223,37.781896,"(37.78189594886033, -122.42822330317604)",18608402109320
3,186072593,NON-CRIMINAL,LOST PROPERTY,Monday,01/01/2018,17:00,MISSION,NONE,2100 Block of MARKET ST,-122.429789,37.766652,"(37.766652147476215, -122.4297889869883)",18607259371000
4,186063279,LARCENY/THEFT,GRAND THEFT FROM LOCKED AUTO,Monday,01/01/2018,22:00,SOUTHERN,NONE,800 Block of BRYANT ST,-122.403405,37.775421,"(37.775420706711, -122.40340479147905)",18606327906244

In [6]:
# Print length of dataframe
len(df)

46668

In [7]:
# assign field name
field_name = 'IncidntNum'

In [8]:
key_field = set(df[field_name].values)
header = True

In [10]:
# add a method to concatenate by field_name
data = pd.concat(g for _, g in df.groupby(field_name) if len(g) >1)
if len(data) > 1:
    print('Found duplicates')
    # Output to CSV
    data.to_csv(file_out_dupes, mode='w', header=header, index=False)
else:
    pass

Found duplicates

In [11]:
dupe_df = pd.read_csv(file_out_dupes)
#dupe_df.set_index('IncidntNum', inplace=True)
dupe_df.head()

,IncidntNum,Category,Descript,DayOfWeek,Date,Time,PdDistrict,Resolution,Address,X,Y,Location,PdId
0,18029933,MISSING PERSON,MISSING JUVENILE,Tuesday,04/17/2018,10:30,PARK,NONE,1600 Block of TURK ST,-122.436275,37.780025,"(37.780024733106465, -122.43627497948137)",1802993374010
1,18029933,RUNAWAY,RUNAWAY,Tuesday,04/17/2018,10:30,PARK,NONE,1600 Block of TURK ST,-122.436275,37.780025,"(37.780024733106465, -122.43627497948137)",1802993329100
2,160468829,WARRANTS,WARRANT ARREST,Thursday,01/11/2018,08:22,SOUTHERN,NONE,800 Block of BRYANT ST,-122.403405,37.775421,"(37.775420706711, -122.40340479147905)",16046882963010
3,160468829,OTHER OFFENSES,FAILURE TO REGISTER AS SEX OFFENDER,Thursday,01/11/2018,08:22,SOUTHERN,NONE,800 Block of BRYANT ST,-122.403405,37.775421,"(37.775420706711, -122.40340479147905)",16046882914020
4,180000122,DRIVING UNDER THE INFLUENCE,DRIVING WHILE UNDER THE INFLUENCE OF ALCOHOL,Monday,01/01/2018,00:32,NORTHERN,"ARREST, BOOKED",WEBSTER ST / OAK ST,-122.429179,37.774182,"(37.774182253014295, -122.42917887616841)",18000012265050

In [13]:
# Sort values to double check
dupe_df.sort_values(by=['IncidntNum'])
dupe_df.head(10)

,IncidntNum,Category,Descript,DayOfWeek,Date,Time,PdDistrict,Resolution,Address,X,Y,Location,PdId
0,18029933,MISSING PERSON,MISSING JUVENILE,Tuesday,04/17/2018,10:30,PARK,NONE,1600 Block of TURK ST,-122.436275,37.780025,"(37.780024733106465, -122.43627497948137)",1802993374010
1,18029933,RUNAWAY,RUNAWAY,Tuesday,04/17/2018,10:30,PARK,NONE,1600 Block of TURK ST,-122.436275,37.780025,"(37.780024733106465, -122.43627497948137)",1802993329100
2,160468829,WARRANTS,WARRANT ARREST,Thursday,01/11/2018,08:22,SOUTHERN,NONE,800 Block of BRYANT ST,-122.403405,37.775421,"(37.775420706711, -122.40340479147905)",16046882963010
3,160468829,OTHER OFFENSES,FAILURE TO REGISTER AS SEX OFFENDER,Thursday,01/11/2018,08:22,SOUTHERN,NONE,800 Block of BRYANT ST,-122.403405,37.775421,"(37.775420706711, -122.40340479147905)",16046882914020
4,180000122,DRIVING UNDER THE INFLUENCE,DRIVING WHILE UNDER THE INFLUENCE OF ALCOHOL,Monday,01/01/2018,00:32,NORTHERN,"ARREST, BOOKED",WEBSTER ST / OAK ST,-122.429179,37.774182,"(37.774182253014295, -122.42917887616841)",18000012265050
5,180000122,OTHER OFFENSES,TRAFFIC VIOLATION ARREST,Monday,01/01/2018,00:32,NORTHERN,"ARREST, BOOKED",WEBSTER ST / OAK ST,-122.429179,37.774182,"(37.774182253014295, -122.42917887616841)",18000012265010
6,180000122,NON-CRIMINAL,IMPOUNDED VEHICLE,Monday,01/01/2018,00:32,NORTHERN,"ARREST, BOOKED",WEBSTER ST / OAK ST,-122.429179,37.774182,"(37.774182253014295, -122.42917887616841)",18000012207053
7,180000172,SECONDARY CODES,PREJUDICE-BASED INCIDENT,Monday,01/01/2018,00:55,MISSION,NONE,100 Block of UTAH ST,-122.406668,37.767770,"(37.76777047915387, -122.40666763740835)",18000017215300
8,180000172,ASSAULT,BATTERY,Monday,01/01/2018,00:55,MISSION,NONE,100 Block of UTAH ST,-122.406668,37.767770,"(37.76777047915387, -122.40666763740835)",18000017204134
9,180000285,OTHER OFFENSES,RESISTING ARREST,Monday,01/01/2018,02:08,MISSION,"ARREST, BOOKED",3300 Block of CESAR CHAVEZ ST,-122.417059,37.748078,"(37.7480778892528, -122.41705938514507)",18000028527170